version: '3.1'
services:
  app:
    container_name: app-gourmet
    image: app-gourmet
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      - sonic
    environment:
      DB_HOST: 172.29.64.1
      DB_PORT: 5432
      DB_NAME: gourmet
      DB_USER: postgres
      DB_PASSWORD: root
      SONIC_HOST: 172.29.64.1
      SONIC_PASSWORD: SecretPassword
  dbpostgresql:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/start.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gourmet
  sonic:
    image: valeriansaliou/sonic:v1.3.0
    container_name: sonic
    ports:
    - "1491:1491"
    volumes:
      - ./sonic/store:/var/lib/sonic/store
      - ./sonic/sonic.cfg:/etc/sonic.cfg
volumes:
  postgres-data:
  sonic-config: