spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

sonic:
  address: ${SONIC_HOST}
  password: ${SONIC_PASSWORD}


server:
  error:
    include-message: always
    include-exception: true